---
panels: true
---

::: {.content-hidden when-meta="panels"}
# Week plan {.unnumbered}
:::

[Schedule for student presentations](https://docs.google.com/spreadsheets/d/1t0UzO-aOj53uVPh39hG9EYR0AvrWdXj-uPFNdFWH660/edit?usp=sharing)

<!-- ------------------------------------------------------------------------------------- -->

## 1 {.unnumbered}

**(Week 5)**

**Monday:** Course intro and overview. Coop chapt 1, 2, 3

**Thursday:** Exercise on [cluster practicals](exercises/cluster_practicals/README.md)

<!-- ------------------------------------------------------------------------------------- -->

## 2 {.unnumbered}

**(Week 6)**

**Monday:** Lecture on the coalescent and the ARG. Coop chapt 4, [Paper: Simons Genome Diversity Project] <!-- [Paper on Platypus] -->

<!-- **Thursday:** [Browsing ARGs](https://munch-group.org/docs/genomic-thinking/exercises/mapping_and_calling) -->

<!-- ------------------------------------------------------------------------------------- -->

## 3 {.unnumbered} 

**(Week 7)** 

**Monday:** Lecture on population structure, incomplete lineage sorting, HMMs. Coop chapt 6, [Review on ILS](https://doi.org/10.1146/annurev-genet-120213-092532)

**Thursday:** Inference of population structure and admixture. GitHub: `munch-group/pca-admixture-exercise`.

<!-- ------------------------------------------------------------------------------------- -->

## 4 {.unnumbered}

**(Week 8)**

**Monday:** Lecture on past population demography, HMMs, PSMC, [Paper on PSMC](https://www.nature.com/articles/nature10231)

**Thursday:** Exercise on estimating past population sizes. GitHub: `munch-group/psmc-exercise`.

<!-- ------------------------------------------------------------------------------------- -->

## 5 {.unnumbered}

**(Week 9)**

**Monday:** Exercise on tree sequences inference. GitHub: `munch-group/relate-tree-exercise`.

**Thursday:** Lecture on Tree sequences, HMMs, ARG [Paper on tree inference](https://www.nature.com/articles/s41588-019-0484-x) 


<!-- ------------------------------------------------------------------------------------- -->

## 6 {.unnumbered}

**(Week 10)**

**Monday:** Tree sequences. *Direct and linked selection*, Coop chapt 12, 13

**Thursday:** Exercise on tree sequence inference (continued). GitHub: `munch-group/relate-tree-exercise`.

<!-- [Review on admixture](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007349),  -->

<!-- [Paper on admixture inference](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007641) -->

<!-- **Thursday:** [Phasing and recombination](https://munch-group.org/docs/genomic-thinking/exercises/phasing) -->

<!-- ------------------------------------------------------------------------------------- -->

## 7 {.unnumbered}

**(Week 11)**

**Monday:** Overview

**Thursday:** Exercise on positive selection

<!-- ------------------------------------------------------------------------------------- -->

## 8 {.unnumbered}

**(Week 12)** 

**Monday:** https://munch-group.org/docs/genomic-thinking/exercises/mapping_and_calling

**Thursday:** Lecture on [GWAS review], [Population stratification review], Coop 99-120 [Mandatory project description](https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Projects)

<!-- ------------------------------------------------------------------------------------- -->

## 9 {.unnumbered}

**(Week 13)** 

**Monday:** Exercise on [GWAS quality control](https://munch-group.org/docs/genomic-thinking/exercises/GWAS_QC)

**Thursday:** Lecture on heritability, [Review on heritability and LMM](https://dl.acm.org/doi/10.1145/2817827) ; Coop Sec 2.2 (p23-36) + Chapt 7 (p119-142)


<!-- ------------------------------------------------------------------------------------- -->

## 10 {.unnumbered}

**(Week 14)** 

**Monday:** [Association testing](https://munch-group.org/docs/genomic-thinking/exercises/GWAS_association)

**Thursday:** HOLYDAY 
 

<!-- ------------------------------------------------------------------------------------- -->

## 11 {.unnumbered}

**(Week 15)**

**Monday:** HOLYDAY

**Thursday:** Exercise on [estimating heritability](https://munch-group.org/docs/genomic-thinking/exercises/heritability)

## 12 {.unnumbered}

<!-- ------------------------------------------------------------------------------------- -->

**(Week 16)**

**Monday:** Project

**Thursday:** HOLYDAY

<!-- ------------------------------------------------------------------------------------- -->

## 13 {.unnumbered}

**(Week 17)**

**Monday:** Project

**Thursday:** Project

<!-- ------------------------------------------------------------------------------------- -->

## 14 {.unnumbered}

**(Week 18)**

**Monday:** Project

**Thursday:** Project



<!-- Curriculum links -->
[Paper: Simons Genome Diversity Project]: https://www.nature.com/articles/nature18964                                                                                                                                                                               
[Paper on Platypus]: https://www.nature.com/articles/ng.3036                                                                                                                                                             
[Paper on PSMC]: https://www.nature.com/articles/nature10231                                                                                                                                                          
[Paper on tree inference]: https://www.nature.com/articles/s41588-019-0484-x
[Review on recombination rate]: https://www.nature.com/articles/s41576-020-0240-1
[Review on ILS]: https://doi.org/10.1146/annurev-genet-120213-092532
[Review on admixture]: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007349
[Paper on admixture inference]: https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007641
[Paper on tree inference]: https://www.nature.com/articles/s41588-019-0484-x                                                                                                                                             
[Paper on exploiting ARGs in GWAS]: https://www.nature.com/articles/s41588-023-01379-x

<!-- https://brightspace.au.dk/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTY2Mjk3LUxSNDA2NTEvYXJnbmVlZGxlLnBkZg/argneedle.pdf?ou=166297 -->

[Tree sequences]: https://munch-group.org/docs/genomic-thinking/exercises/tree_sequences
[GWAS review]: https://
[Population stratification review]: https://
[Review on heritability and LMM]: https://dl.acm.org/doi/10.1145/2817827
[Genetic architecture review]: https://
[Article on "omnigenic" model]: https://

<!-- Exercise links -->
[Cluster practicals]: https://munch-group.org/docs/genomic-thinking/exercises/cluster_practicals
[Read mapping and base calling]: https://munch-group.org/docs/genomic-thinking/exercises/mapping_and_calling
[Estimating past population sizes]: https://munch-group.org/docs/genomic-thinking/exercises/demography
[Estimating past population sizes]: https://munch-group.org/docs/genomic-thinking/exercises/demography
[Phasing and recombination]: https://munch-group.org/docs/genomic-thinking/exercises/phasing
[Inference of population structure and admixture]: https://munch-group.org/docs/genomic-thinking/exercises/population_structure
[Detecting archaic ancestry in modern humans]: https://munch-group.org/docs/genomic-thinking/exercises/admixture
[Tree sequences]: https://munch-group.org/docs/genomic-thinking/exercises/tree_sequences
[Inference of positive selection]: https://munch-group.org/docs/genomic-thinking/exercises/selection
[GWAS quality control]: https://munch-group.org/docs/genomic-thinking/exercises/GWAS_QC
[Association testing]: https://munch-group.org/docs/genomic-thinking/exercises/GWAS_association
[Estimating heritability]: https://munch-group.org/docs/genomic-thinking/exercises/heritability

<!-- Project links -->
[Mandatory project description]: https://github.com/kaspermunch/PopulationGenomicsCourse/tree/master/Projects
